# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_service import voxia_pb2 as voxia__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voxia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoxIAServiceStub(object):
    """─── Servicio principal de análisis de audio ──────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeText = channel.unary_unary(
                '/voxia.VoxIAService/AnalyzeText',
                request_serializer=voxia__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=voxia__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/voxia.VoxIAService/HealthCheck',
                request_serializer=voxia__pb2.HealthRequest.SerializeToString,
                response_deserializer=voxia__pb2.HealthResponse.FromString,
                _registered_method=True)


class VoxIAServiceServicer(object):
    """─── Servicio principal de análisis de audio ──────────────────────────────────
    """

    def AnalyzeText(self, request, context):
        """Analiza texto ya transcrito y devuelve resumen, puntos clave, tareas y decisiones
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Devuelve el estado de salud del servidor gRPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoxIAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=voxia__pb2.AnalyzeRequest.FromString,
                    response_serializer=voxia__pb2.AnalyzeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=voxia__pb2.HealthRequest.FromString,
                    response_serializer=voxia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voxia.VoxIAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voxia.VoxIAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoxIAService(object):
    """─── Servicio principal de análisis de audio ──────────────────────────────────
    """

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voxia.VoxIAService/AnalyzeText',
            voxia__pb2.AnalyzeRequest.SerializeToString,
            voxia__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voxia.VoxIAService/HealthCheck',
            voxia__pb2.HealthRequest.SerializeToString,
            voxia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
