# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voxia.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voxia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoxia.proto\x12\x05voxia\"6\n\x0e\x41nalyzeRequest\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"\x80\x01\n\x0f\x41nalyzeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x12\n\nkey_points\x18\x02 \x03(\t\x12\r\n\x05tasks\x18\x03 \x03(\t\x12\x11\n\tdecisions\x18\x04 \x03(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x88\x01\n\x0cVoxIAService\x12<\n\x0b\x41nalyzeText\x12\x15.voxia.AnalyzeRequest\x1a\x16.voxia.AnalyzeResponse\x12:\n\x0bHealthCheck\x12\x14.voxia.HealthRequest\x1a\x15.voxia.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voxia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=22
  _globals['_ANALYZEREQUEST']._serialized_end=76
  _globals['_ANALYZERESPONSE']._serialized_start=79
  _globals['_ANALYZERESPONSE']._serialized_end=207
  _globals['_HEALTHREQUEST']._serialized_start=209
  _globals['_HEALTHREQUEST']._serialized_end=224
  _globals['_HEALTHRESPONSE']._serialized_start=226
  _globals['_HEALTHRESPONSE']._serialized_end=275
  _globals['_VOXIASERVICE']._serialized_start=278
  _globals['_VOXIASERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
